### ISSUE TITLE
Warp not getting Killed when the program gets a new Applicant

### ISSUE THREAD

**Issue by Voreck** [bongotastic/Headlines#129]
Well, the issue is exactly what the title says. After some time (don't remember if just randomly or after an update) it stopped working. To verify I didnt just imagine things I opened the recruit panel and initiated time warp. A new Recruit popped up (also got a notification in one of those message boxes on the bottom right) but warp didn't get killed

[The log and the safe file](https://github.com/bongotastic/Headlines/files/7243434/log.%2B.safe.zip)

**Comment by bongotastic** [comment]
Progress: 
After two new applicant events, the following shows up: 
`[EXC 12:59:38.777] ArgumentException: Getting control 0's position in a group with only 0 controls when doing repaint
Aborting
	UnityEngine.GUILayoutGroup.GetNext () (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayoutUtility.DoGetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayoutUtility.GetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.DoLabel (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.Label (System.String text, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	Headlines.source.GUI.HeadlinesGUIManager.DrawRecruitmentPanel () (at <2cd51777a46c4556aa958ad53309357a>:0)
	Headlines.source.GUI.HeadlinesGUIManager.DrawWindow (System.Int32 windowID) (at <2cd51777a46c4556aa958ad53309357a>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

**Comment by Voreck** [comment]
In that exact save its still happening
[KSP.zip]Here's the zip(https://github.com/bongotastic/Headlines/files/7272870/KSP.zip)

**Comment by bongotastic** [comment]
Note to self: three errors in last uploaded log file that needs to be dealt with. Possible overlap with issue #135.

**Comment by bongotastic** [comment]
Error 1:
`[ERR 09:01:59.176] Exception loading ScenarioModule PeopleManager: System.ArgumentNullException: Value cannot be null.
Parameter name: value
  at System.Boolean.Parse (System.String value) [0x00003] in <ad04dee02e7e4a85a1299c7ee81c79f6>:0 
  at Headlines.PersonnelFile.FromConfigNode (ConfigNode node) [0x000c4] in <d7cc98c05b274086b3e3f6750dc6305f>:0 
  at Headlines.PersonnelFile..ctor (ConfigNode node) [0x00097] in <d7cc98c05b274086b3e3f6750dc6305f>:0 
  at Headlines.PeopleManager.OnLoad (ConfigNode node) [0x0005a] in <d7cc98c05b274086b3e3f6750dc6305f>:0 
  at ScenarioModule.Load (ConfigNode node) [0x0000e] in <c1858a3f77504bd1aaa946fdccf84670>:0 
  at ScenarioRunner.AddModule (ConfigNode node) [0x0005e] in <c1858a3f77504bd1aaa946fdccf84670>:0 `

Should be taken care of with refactor https://github.com/bongotastic/Headlines/commit/402e40d1001a2e1abc56e7fe07f37897a813f34e

**Comment by bongotastic** [comment]
Error: 
`[LOG 09:03:06.671] [Headlines] Triggering HMM position_search
[LOG 09:03:06.673] [Headlines] HMM position_search fires new_applicant
[LOG 09:03:06.673] [Headlines] [Emission] new_applicant at time 1956-01-27 21:38:42
[LOG 09:03:06.696] [Headlines] Adding Jeffery Johnson to as Pilot
[LOG 09:03:06.702] [Headlines] Generating label event_text from emission new_applicant
[LOG 09:03:06.702] [Headlines][NEWSLETTER] New competent applicant
[LOG 09:03:06.702] [[[We received in the mail a new application from Friedrich Becker, a excellent Pilot.
During the interview, the candidate proved to be stubborn.
]]]
[LOG 09:03:06.703] [Headlines] New Applicant to review
[LOG 09:03:06.703] [[New Applicant to review]]
[LOG 09:03:06.703] [Headlines] HMM position_search transitions to position_search
[LOG 09:03:06.703] [Headlines] Rescheduling HMM position_search to +1187438.39893651
[LOG 09:03:06.703] [Headlines] Triggering HMM program_manager
[LOG 09:03:06.706] [Headlines] HMM program_manager fires program_check
[LOG 09:03:06.706] [Headlines] [Emission] program_check at time 1956-01-27 21:38:42
[LOG 09:03:06.706] [Headlines] HMM program_manager transitions to program_manager
[LOG 09:03:06.706] [Headlines] Rescheduling HMM program_manager to +81029.4124911207
[LOG 09:03:06.706] [Headlines] Triggering HMM Henning Wagner@role_Pilot
[LOG 09:03:06.708] [Headlines] HMM Henning Wagner@role_Pilot fires 
[LOG 09:03:06.709] [Headlines] HMM Henning Wagner@role_Pilot transitions to role_Pilot
[LOG 09:03:06.709] [Headlines] Rescheduling HMM Henning Wagner@role_Pilot to +2403862.8040184
[LOG 09:03:06.709] [Headlines] Triggering HMM Anneliese Wagner@role_Pilot
[LOG 09:03:06.712] [Headlines] HMM Anneliese Wagner@role_Pilot fires media_blitz
[LOG 09:03:06.714] [Headlines] HMM Anneliese Wagner@role_Pilot transitions to role_Pilot
[LOG 09:03:06.714] [Headlines] Rescheduling HMM Anneliese Wagner@role_Pilot to +4168414.40943604
[LOG 09:03:06.714] [Headlines] News Feed at 4 elements
[LOG 09:03:06.714] [RP-0] MaintenanceHandler removing -32.6740849408598 funds
[EXC 09:03:06.741] ArgumentException: Getting control 0's position in a group with only 0 controls when doing repaint
Aborting
	UnityEngine.GUILayoutGroup.GetNext () (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayoutUtility.DoGetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayoutUtility.GetRect (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.DoLabel (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUILayout.Label (System.String text, UnityEngine.GUILayoutOption[] options) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	Headlines.source.GUI.HeadlinesGUIManager.DrawRecruitmentPanel () (at <d7cc98c05b274086b3e3f6750dc6305f>:0)
	Headlines.source.GUI.HeadlinesGUIManager.DrawWindow (System.Int32 windowID) (at <d7cc98c05b274086b3e3f6750dc6305f>:0)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (System.Int32 windowID) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI+WindowFunction func, System.Int32 id, System.Int32 instanceID, UnityEngine.GUISkin _skin, System.Int32 forceRect, System.Single width, System.Single height, UnityEngine.GUIStyle style) (at <fa6f9762ac624af092525d37c9d516c4>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)`

**Comment by bongotastic** [comment]
@Voreck , thanks for your continued reporting. I can't reproduce the issue as it works 100% of the time for me. The best that I can do it to try to anticipate what *may* cause the issue for you and change the code to make it work. I can't promise that this is a fix, but I hope.
