### ISSUE TITLE
Crew proficiency training disappears after mission completion

### ISSUE THREAD

**Issue by KalynnDarcy** [bongotastic/Headlines#133]
As the title says.

I have a pretty standard RP1 install, I believe the only thing I have different from the express is conformal decals and Kerbal Konstructs for the extra launch sites and runways.

I send my Kerbal on a (successful) X-plane mission, and when I recover it to SPH from landing, they suddenly do not have their previous proficiency in the X-1, and require another 45 days course to get it back. I removed headlines, loaded a save, and ran the same mission again, and upon recovery they retained their proficiency training.

**Comment by KalynnDarcy** [comment]
Update: I added the newest 0.5 Headlines back and ran the same mission again.

**Comment by bongotastic** [comment]
@KalynnDarcy , thanks for reporting. I suspect that this is an issue with KCT's component of RP1 since Headlines doesn't share memory objects with it, and proficiency training is on the RP1 side. In fact, Headlines does not even read them. I'll ask the RP1 dev if this issue rings a bell for them.

**Comment by KalynnDarcy** [comment]
Could this be caused at all by having 'career progress logging' disabled in the RP-1 section of the new career options? I don't know if Headlines uses that to track anything, but since I don't really ever plan to upload a career log, I normally disable it to make my persistent file less bloated.

While trying to narrow down the cause of the proficiency training issue, I've noticed having that option on or off seems to  have an effect on whether the starting four pilots obey the 'Preserve original traits' option from Kerbal Renamer. Will test further to see if it also causes the training bug.

**Comment by bongotastic** [comment]
Headlines isn't touching this. I think that this is a RP1 issue. Disabling career logging *may* be a thread to follow. I've been playing with Renamer in recent past (the new multicultural names), but then again disabling event logger having an impact on Renamer is also counterintuitive. I will point this out to our resident expert when it comes to career logging.

**Comment by NathanKell** [comment]
@siimav will know for sure but AFAIK career logging should have no effect on training, career logging isn't kerbal flight logging (training is represented by flight log events).

Just to double check, when your kerbal goes back to active duty the proficiency doesn't return?

**Comment by KalynnDarcy** [comment]
I've tested quite a few times now, and the proficiency doesn't return when they return to duty.

I've done this now with a clean express install, the only additions being Headlines and @bongotastic 's Kerbal Renamer fork. If I enable career logging, everything seems to work as normal.

Things that only happen when I disable career logging:

- My starting 4 Kerbals have random traits (my last attempt I got 1 pilot and 3 engineers) even though I have 'preserve original traits' enabled. 
- Kerbals will sometimes change professions especially in the first few days of a career (I was unsure if this was part of Headlines?)
- Proficiency training disappears after recovery from a mission.

So far, I haven't had any of these issues happen with headlines removed, whether I have career logging on or off.

**Comment by KalynnDarcy** [comment]
Hmm. After more testing, these could be unrelated. The career logging _does_ seems to reliably affect the Kerbal starting traits and whether they stay as they were at career start, so maybe that is a separate Kerbal Renamer issue. 

Because one of my tests got the training bug even with career logging on, so that one appears separate. And I'm now noticing that sometimes I finish a mission, recover it, and I don't get the "mission training expired" message shortly after. That is when they are missing proficiency. If their mission training expires, they keep their proficiency. I'm not sure how this could be Headlines related, but so far I haven't been able to reproduce it in a clean install with no Headlines.

**Comment by NathanKell** [comment]
Mission training is removed when the crew handler next processes all kerbals, which might be a little bit after the recovery of the mission (crew are updated every hour). I have often not gotten that message until later, but it does always show up for me. Note that when you recover a flight, mission training expiration time is set to the UT when the craft was recovered ( https://github.com/KSP-RO/RP-0/blob/master/Source/Crew/CrewHandler.cs#L461 ) but crew data is *processed* later, rather than immediately (so as not to process every tick). See here https://github.com/KSP-RO/RP-0/blob/master/Source/Crew/CrewHandler.cs#L187 where the update logic is run once every ingame hour. Try warping a couple hours after recovering the flight and you should get the expirations.

**Comment by KalynnDarcy** [comment]
What you describe is certainly how its always worked for me with a standard install. Yet for some reason with Headlines installed, it intermittently doesn't do that. More often than not, I experience what happens in the attached story of screenshots

![Career Start](https://user-images.githubusercontent.com/16504935/135566604-1b2e02bb-a597-4ea1-bd2e-ab71c68d8de7.jpg)
![Profession changes 32 seconds after career start](https://user-images.githubusercontent.com/16504935/135566608-f5d280e3-a337-453b-818e-17a8b477f08c.jpg)
![Pre-launch, with proficiency and mission training completed](https://user-images.githubusercontent.com/16504935/135566609-d74cdae7-618e-4345-b850-966001dfb01c.jpg)
![Recovery after launch](https://user-images.githubusercontent.com/16504935/135566612-f439787e-b0bc-4f27-9991-7bce51b184a5.jpg)
![Immediately after recovery, no trainings visible](https://user-images.githubusercontent.com/16504935/135566613-b30387c1-5ee8-45c2-a859-394e8a72f053.jpg)
![16 days later, returned to duty, no trainings.](https://user-images.githubusercontent.com/16504935/135566616-f61774b2-acf0-46ad-a7da-fcf60fb51213.jpg)

At no time after recovery did I see the "mission training expired" text flash up.
I repeated the same steps on a new career without Headlines, and my Kerbals did not change professions, my mission training expired about an hour after recovery, and my pilot retained their proficiency.

**Comment by bongotastic** [comment]
The change in specialty is deliberate and meant to override RP1's delayed conversion of all crew members to pilots. I really can't see how Headlines would do this, but this doesn't mean that I'm right to think them as unrelated. Do you have a savefile from after you observe the loss of training. A Log file could also be useful.

**Comment by bongotastic** [comment]
![careerlog](https://user-images.githubusercontent.com/8598546/135607544-c1a3c0d1-78d9-4f56-bb94-a932775ef179.png)

This is a sample careerlog of a pilot who flew three xplane mission. I wonder what yours look like.

**Comment by KalynnDarcy** [comment]
Mine looks like this after I recover the flight.

![f747e263f9f7e399ea4f7fa136109ce8](https://user-images.githubusercontent.com/16504935/135677313-510ad8f4-3803-4727-8b25-3020604b0ff9.png)

Save file and log:
[Save_and_Log.zip](https://github.com/bongotastic/Headlines/files/7269758/Save_and_Log.zip)

**Comment by KalynnDarcy** [comment]
Oops. I meant to zip up the whole save, not just the persistent file, not sure if you wanted the whole thing, but here it is with the whole folder just in case.
[Save_Log_Headlines.zip](https://github.com/bongotastic/Headlines/files/7269864/Save_Log_Headlines.zip)

Also, after grabbing that one, I loaded up KSP without headlines, started a new career with identical settings, and took the same steps as before, with the same test craft. After I recovered, my pilot still had their proficiency. Their crew log in the .sfs looks like it should.
![db2807a916e4bde81e454ce826ffcce0](https://user-images.githubusercontent.com/16504935/135679852-089f3a49-d62c-403f-b874-1dee9eab2169.png)

I attached that save and log too if it helps. The only thing I did between was remove headlines. 
[Save_Log_No_Headlines.zip](https://github.com/bongotastic/Headlines/files/7269876/Save_Log_No_Headlines.zip)

**Comment by bongotastic** [comment]
Thanks. 
1. This is with Career logging turned off still? 
2. Had your crew member have 0 experience before the flight?

**Comment by KalynnDarcy** [comment]
Yes, career logging was off. As I said though, I did have the issue occur on one of my tests yesterday with career logging on, so its possible I was seeing a false correlation there? 

I believe they did have 0 experience, I did this immediately on starting a new save, so they were just the starting Kerbals.

**Comment by bongotastic** [comment]
Thanks. This is a tricky thing. I'll try to reproduce the issue on my testing install with logging off to see if this should be ruled out.

**Comment by KalynnDarcy** [comment]
Okay. So, your question about experience had me running more tests. Turns out the career logging thing was an unrelated co-incidence. 1 star kerbals are unaffected. They retain their proficiency as normal. But 0 star kerbals seem to always lose their proficiency.

**Comment by bongotastic** [comment]
The issue was identified with the help of a someone on the RP1 team. I will release a fix within a day or so. Thankful of the time you spent on this!

**Comment by KalynnDarcy** [comment]
Awesome! :D Thanks for getting onto it all so quick. And thanks for putting in all the time in this mod in general, from what I have played of it so far, it seems like a lot of fun!

**Comment by bongotastic** [comment]
New release v0.5.6-beta is out with a fix.
